#!/bin/bash

source $(dirname $0)/../scripts/common_source.sh

ESRLPATH="$PROJROOT/ext/easysrl"
PIDFILE=$1
LOGFILE=$2
shift
shift
VERSION="0.1.0"

[ -e $ESRLPATH/build/libs/easysrl-${VERSION}-capsule.jar ] || die "$ESRLPATH/build/libs/easysrl-$VERSION-capsule.jar missing, run gradle build"
[ -e $ESRLPATH/model/text/categories ] || die "$ESRLPATH/model/text missing, run scripts/extract_lfs.sh"

EXEC="java -jar $ESRLPATH/build/libs/easysrl-$VERSION-capsule.jar --model $ESRLPATH/model/text --daemonize -l 250 $*"
if [ "x$PIDFILE" == "x" ]; then
	$EXEC
else 
	if [ "x$LOGFILE" == "x" ]; then
		nohup $EXEC &
	else
		nohup $EXEC > $LOGFILE &
	fi
	PID="$!"
	echo "$PID" > $PIDFILE
fi
