#!/bin/bash

source $(dirname $0)/../scripts/common_source.sh

ECCGPATH="$PROJROOT/ext/easyccg"
PIDFILE=$1
LOGFILE=$2
VERSION="0.1.0"

[ -e $ECCGPATH/build/libs/easyccg-${VERSION}-capsule.jar ] || die "$ECCGPATH/build/libs/easyccg-$VERSION-capsule.jar missing, run gradle build"
[ -e $PROJROOT/build/libs/ie-${VERSION}.jar ] || die "$PROJROOT/build/libs/ie-$VERSION.jar missing, run gradle build"
[ -e $ECCGPATH/model/text/categories ] || die "$ECCGPATH/model/text missing, run scripts/extract_lfs.sh"

EXEC="java -jar $ECCGPATH/build/libs/easyccg-$VERSION-capsule.jar --model $ECCGPATH/model/text --daemonize"
if [ "x$PIDFILE" == "x" ]; then
	$EXEC
else 
	if [ "x$LOGFILE" == "x" ]; then
		nohup $EXEC &
	else
		nohup $EXEC > $LOGFILE &
	fi
	PID="$!"
	echo "$PID" > $PIDFILE
fi
